<!--<!DOCTYPE html>

<html lang="en"> 
<head>

<meta name="viewport" content="width = 1050, user-scalable = no" />
<script type="text/javascript" src="js/jquery.min.1.7.js"></script>
<script type="text/javascript" src="js/modernizr.2.5.3.min.js"></script>
<link rel="stylesheet" href="css/basic.css" type="text/css" />


</head>

<body>

<div class="flipbook-viewport">
	<div class="container">
		<div class="flipbook">
			<div style="background-image:url(media/madame-modern/1.jpg)"></div>
			<div style="background-image:url(media/madame-modern/2.jpg)"></div>
			<div style="background-image:url(media/madame-modern/3.jpg)"></div>
			<div style="background-image:url(media/madame-modern/4.jpg)"></div>
			<div style="background-image:url(media/madame-modern/5.jpg)"></div>
			<div style="background-image:url(media/madame-modern/6.jpg)"></div>
			<div style="background-image:url(media/madame-modern/7.jpg)"></div>
			<div style="background-image:url(media/madame-modern/8.jpg)"></div>
			<div style="background-image:url(media/madame-modern/9.jpg)"></div>
			<div style="background-image:url(media/madame-modern/10.jpg)"></div>
			<div style="background-image:url(media/madame-modern/11.jpg)"></div>
			<div style="background-image:url(media/madame-modern/12.jpg)"></div>
		</div>
	</div>
</div>


<script type="text/javascript">

function loadApp() {

	// Create the flipbook

	$('.flipbook').turn({
			// Width

			width:922,
			
			// Height

			height:600,

			// Elevation

			elevation: 50,
			
			// Enable gradients

			gradients: true,
			
			// Auto center this flipbook

			autoCenter: true

	});
}

// Load the HTML4 version if there's not CSS transform

yepnope({
	test : Modernizr.csstransforms,
	yep: ['js/turn.js'],
	nope: ['js/turn.html4.min.js'],
	both: ['css/basic.css'],
	complete: loadApp
});

</script>

</body>
</html>